sudo: required
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

services:
  - docker

before_install:
  - docker build -t unicef/magicbox-aggregate-mobility .
  - docker run -d -v $(pwd)/data:/app/data:z unicef/magicbox-aggregate-mobility /bin/bash -c "node main.js"
  - docker ps -a
  - docker run -v $(pwd)/data:/app/data:z unicef/magicbox-aggregate-mobility /bin/bash -c "node main.js"

